name: dart_message_bus
description: A useful implementation of publish–subscribe messaging pattern using Dart Stream.
version: 0.0.1
homepage: https://github.com/javad-amiry/dart_message_bus
author: javad amiry <javad.d.amiry@gmail.com>

environment:
  sdk: '>=1.0.0'

dev_dependencies:
  test: ^0.12.0
